#!/bin/bash

echo "📝 GitHub 登录配置指南"
echo "================================"
echo ""
echo "当前容器环境无法直接安装 GitHub CLI，但你可以用以下方式："
echo ""
echo "方案 1: 使用 Git Credential Helper（推荐）"
echo "----------------------------------------"
echo "在宿主机上设置环境变量："
echo "export GITHUB_TOKEN='你的 GitHub Personal Access Token'"
echo ""
echo "然后运行："
echo "git config --global credential.helper store"
echo "git config --global url.\"https://\$GITHUB_TOKEN@github.com/\".insteadOf \"https://github.com/\""
echo ""
echo "方案 2: 直接在 URL 中使用 Token"
echo "--------------------------------"
echo "git clone https://\$GITHUB_TOKEN@github.com/username/repo.git"
echo ""
echo "方案 3: 在宿主机操作后挂载"
echo "--------------------------------"
echo "在宿主机上:"
echo "  1. 克隆仓库到本地目录"
echo "  2. Docker 挂载该目录到容器"
echo ""
echo "================================"
echo "你需要哪个方案的详细步骤？"
